server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:ysuser@localhost:1001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5                # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10            # 发呆时间，即服务续约到期时间（缺省为90s）
spring:
  application:
    name: base-cloud-upload
base:
  cloud:
    upload:
      path: E:/upload_files/                            #/www/wwwroot/upload_files/                  #文件存储路径